[package]
name = "m4b-maker"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.26"
rfd = "0.12"           # File dialogs
rodio = "0.17"         # Audio playback
tempfile = "3.8"       # Temporary files
which = "6.0"          # Check for ffmpeg